version: "3.1"
services:
  frontend:
    build: node
    container_name: crypto_frontend
    restart: always
    volumes:
      - ../frontend:/app
    working_dir: /app
    command: bash -c "yarn install && yarn start"
    ports:
      - 3000:3000
    networks:
      - crypto_backend
      - crypto_frontend

  backend:
    build: node
    container_name: crypto_api
    restart: always
    volumes:
      - ../api:/api
    working_dir: /api
    command: bash -c "npm install && npm run start:dev"
    ports:
      - 3001:3001
    networks:
      - crypto_backend
      - crypto_frontend

  workspace:
    build: workspace
    container_name: crypto_workspace
    restart: always
    tty: true
    volumes:
      - ../:/app
    working_dir: /app
    networks:
      - crypto_backend
      - crypto_frontend

networks:
  crypto_backend:
    driver: bridge
  crypto_frontend:
    driver: bridge
